export const AdminBookInputField = [
  {
    id: "name",
    name: "name",
    label: "Book Name",
    type: "text",
    startIcon: <></>,
    endIcon: <></>,
    endIconSwap: <></>,
    required: true,
    autoFocus: true,
  },
  {
    id: "photo",
    name: "photo",
    label: "Image Address",
    type: "text",
    startIcon: <></>,
    endIcon: <></>,
    endIconSwap: <></>,
    required: true,
    autoFocus: true,
  },
  {
    id: "summary",
    name: "summary",
    label: "Summary",
    type: "text",
    startIcon: <></>,
    endIcon: <></>,
    endIconSwap: <></>,
    required: true,
    autoFocus: true,
  },
  {
    id: "releases_time",
    name: "releases_time",
    label: "Release Year",
    type: "text",
    startIcon: <></>,
    endIcon: <></>,
    endIconSwap: <></>,
    required: true,
    autoFocus: true,
  },
  {
    id: "rating",
    name: "rating",
    label: "Rating",
    type: "text",
    startIcon: <></>,
    endIcon: <></>,
    endIconSwap: <></>,
    required: true,
    autoFocus: true,
  },
];
